### ISSUE TITLE
Variable declaration and initialization can be done with for loop declaration

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj#1]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj/blob/fc1184764bdb8d22a274c40591e81623a80f6a04/index.js#L16-L17

**Comment by Sandeep-raj** [comment]
Variable declaration and initialization is done inside loop
