### ISSUE TITLE
For loop can be replaced with the Array.prototype.map

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj#2]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj/blob/fc1184764bdb8d22a274c40591e81623a80f6a04/index.js#L17

**Comment by Sandeep-raj** [comment]
for loop is replaced by array.map to map the characters form the given Map
