### ISSUE TITLE
Check if window.onload is required

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj#3]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-Sandeep-raj/blob/fc1184764bdb8d22a274c40591e81623a80f6a04/index.js#L23-L26

**Comment by Sandeep-raj** [comment]
No need of window.onload , directly added event listener to the button
